import { Course } from "@/interfaces/course";


export const data : Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Introduction to Computers',
    description: 'Our Introduction to Computer course is designed for beginners who want to build a strong foundation in technology. You will learn about computer hardware, software, operating systems, and essential applications used in daily life and work. This course makes it easy to understand how computers function and how to use them effectively, giving you the confidence to navigate the digital world with ease.',
    duration: '3 Months',
    rating: 5,
    ratingCount: 8,
    category: 'Basic',
  },
  {
    id: 2,
    cover: '/images/courses/sai-kiran-anagani-5Ntkpxqt54Y-unsplash.jpg',
    title: 'Introduction to Programming',
    description: 'Our Introduction to Programming course is the perfect starting point for beginners who want to explore the world of coding. You’ll learn the fundamentals of programming using popular languages like Java, Python, and PHP. From writing simple programs to understanding core concepts such as variables, loops, and functions, this course equips you with practical skills to solve problems, build applications, and prepare for advanced coding journeys.',
    duration: '12 weeks',
    rating: 5,
    ratingCount: 8,
    category: 'Advanced',
  },
  {
    id: 3,
    cover: '/images/courses/joel-filipe-jU9VAZDGMzs-unsplash.jpg',
    title: 'Autocad, Inventor & Solidworks',
    description: 'This course is designed for students and professionals who want to master 2D drafting and 3D modeling with industry-standard tools like AutoCAD, Inventor, and SolidWorks. You’ll learn how to design, visualize, and create technical drawings and models used in engineering, manufacturing, and product design. Gain practical, hands-on experience that builds your creativity and prepares you for real-world projects in mechanical and industrial design.',
    duration: '12 weeks',
    rating: 5,
    ratingCount: 8,
    category: 'Advanced',
  },
  {
    id: 4,
    cover: '/images/courses/charlesdeluvio-GlavtG-umzE-unsplash.jpg',
    title: 'GST & Tally',
    description: 'Our GST & Tally course is designed to help students, professionals, and business owners manage accounting and taxation with confidence. You’ll learn how to maintain accounts, generate invoices, record transactions, and apply GST rules using Tally software. This course combines practical training with real-world scenarios, enabling you to handle financial records accurately, stay compliant with tax regulations, and improve your career or business efficiency.',
    duration: '12 weeks',
    rating: 5,
    ratingCount: 8,
    category: 'Advanced',
  },
  {
    id: 5,
    cover: '/images/courses/eyestetix-studio-2GZeMyrkfK0-unsplash.jpg',
    title: 'Graphic Design',
    description: 'Our Graphic Design course introduces you to the creative world of visual communication using Photoshop and Illustrator. You’ll learn essential design principles, photo editing, digital illustration, and how to create professional logos, posters, and marketing materials. With hands-on projects and practical exercises, this course builds both your technical skills and creative confidence, preparing you to design visually stunning graphics for personal, academic, or professional purposes.',
    duration: '12 weeks',
    rating: 5,
    ratingCount: 8,
    category: 'Advanced',
  },
  {
    id: 6,
    cover: '/images/courses/construction-4216751_640.jpg',
    title: 'Surveying',
    description: 'Our Surveying course provides a complete introduction to land measurement, mapping, and fieldwork techniques used in civil engineering and construction. You’ll learn about modern surveying instruments, data collection, leveling, contouring, and the preparation of accurate maps and plans. With a balance of theory and practical training, this course equips you with the essential skills required for site planning, design, and real-world engineering projects.',
    duration: '12 weeks',
    rating: 5,
    ratingCount: 8,
    category: 'Vocational',
  },
  {
    id: 7,
    cover: '/images/courses/madison-lavern-CDJCAcAAPlU-unsplash.jpg',
    title: 'Yoga',
    description: 'Our Yoga course is designed to improve both physical and mental well-being through guided practices of postures, breathing techniques, and meditation. You’ll learn how to enhance flexibility, strength, and focus while reducing stress and promoting inner peace. Suitable for beginners as well as those with experience, this course helps you adopt yoga as a lifestyle practice, bringing balance, energy, and positivity into your daily life.',
    duration: '12 weeks',
    rating: 5,
    ratingCount: 8,
    category: 'Vocational',
  }
]